---
title: "cmml/cord biological reps simulation"
author: "Christian La France"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(Signac)
library(SeuratObject)
library(ggplot2)
library(nortest)
```


```{r}
query_object_with_PT = readRDS("C:/Users/chris/Downloads/cord-cmml-granja-mapped-with-median-PT_no_clusters_0_13.rds")
```


Organize data:

```{r}
cord_cmml_medians <- FetchData(query_object_with_PT, vars = c("orig.ident", "median_pseudotime")) %>% group_by(orig.ident) %>% as.data.frame()

ggplot() + geom_density(data=cord_cmml_medians, aes(x=median_pseudotime, group=orig.ident, fill=orig.ident), alpha=0.5) + labs(title="Density of pseudotime values")
```


```{r}
cord_PTs <- cord_cmml_medians[cord_cmml_medians$orig.ident=="cord", ]
cmml_PTs <- cord_cmml_medians[cord_cmml_medians$orig.ident=="cmml", ]
```


### Simulate biological replicates from original data (probably not as useful).
```{r}
n_cord = nrow(cord_PTs) * 0.8
n_cmml = nrow(cmml_PTs) * 0.8

simulated_cord_PTs <- data.frame(cord_sample_1=sample(x=cord_PTs$median_pseudotime, size=n_cord, replace=TRUE), 
                                 cord_sample_2=sample(x=cord_PTs$median_pseudotime, size=n_cord, replace=TRUE),
                                 cord_sample_3=sample(x=cord_PTs$median_pseudotime, size=n_cord, replace=TRUE),
                                 cord_sample_4=sample(x=cord_PTs$median_pseudotime, size=n_cord, replace=TRUE),
                                 cord_sample_5=sample(x=cord_PTs$median_pseudotime, size=n_cord, replace=TRUE))

simulated_cmml_PTs <- data.frame(cmml_sample_1=sample(x=cmml_PTs$median_pseudotime, size=n_cmml, replace=TRUE), 
                                 cmml_sample_2=sample(x=cmml_PTs$median_pseudotime, size=n_cmml, replace=TRUE), 
                                 cmml_sample_3=sample(x=cmml_PTs$median_pseudotime, size=n_cmml, replace=TRUE), 
                                 cmml_sample_4=sample(x=cmml_PTs$median_pseudotime, size=n_cmml, replace=TRUE), 
                                 cmml_sample_5=sample(x=cmml_PTs$median_pseudotime, size=n_cmml, replace=TRUE))


ggplot(simulated_cord_PTs) + 
  geom_density(aes(x=cord_sample_1)) + 
  geom_density(aes(x=cord_sample_2)) + 
  geom_density(aes(x=cord_sample_3)) +
  geom_density(aes(x=cord_sample_4)) + 
  geom_density(aes(x=cord_sample_5)) + 
  labs(title="Simulated cord biological replicates (n = 5)") +
  xlab("Simulated cord pseudotime")

ggplot(simulated_cmml_PTs) + 
  geom_density(aes(x=cmml_sample_1)) + 
  geom_density(aes(x=cmml_sample_2)) + 
  geom_density(aes(x=cmml_sample_3)) +
  geom_density(aes(x=cmml_sample_4)) + 
  geom_density(aes(x=cmml_sample_5)) +
  labs(title="Simulated cmml biological replicates (n = 5)") +
  xlab("Simulated CMML pseudotime")

```



```{r}
# for stats
n_cord = nrow(cord_PTs)
n_cmml = nrow(cmml_PTs)

cord_mean_pt <- mean(cord_PTs$median_pseudotime, rm.na=TRUE)
cmml_mean_pt <- mean(cmml_PTs$median_pseudotime, rm.na=TRUE)

cord_pt_sd <- sd(cord_PTs$median_pseudotime)
cmml_pt_sd <- sd(cmml_PTs$median_pseudotime)
```


### Simulate biological reps from normal distribution
```{r}
n = 5 # number of biological replicates

# this will include some negative pseudotime values. We may need to find a way
# around this. Cannot use abs() because this would skew away from a normal
# distribution. 

cord_rand_normal <- data.frame(sample1 = rnorm(n=n_cord, mean=cord_mean_pt, sd=cord_pt_sd))
cmml_rand_normal <- data.frame(sample1= rnorm(n=n_cmml, mean=cmml_mean_pt, sd=cmml_pt_sd))

for (i in 2:n) {
  col_name <- paste("sample", i, sep="")
  cord_rand_normal[col_name] <- rnorm(n=n_cord, mean=cord_mean_pt, sd=cord_pt_sd)
  cmml_rand_normal[col_name] <- rnorm(n=n_cmml, mean=cmml_mean_pt, sd=cmml_pt_sd)
}

cord_rand_normal <- pivot_longer(cord_rand_normal, 
                                 cols=c("sample1", "sample2", "sample3", "sample4", "sample5"), 
                                 names_to = "sample",
                                 values_to="pseudotime")

cmml_rand_normal <- pivot_longer(cmml_rand_normal, 
                                 cols=c("sample1", "sample2", "sample3", "sample4", "sample5"), 
                                 names_to = "sample",
                                 values_to="pseudotime")


ggplot(data=cord_rand_normal, aes(x=pseudotime, group=sample)) + geom_density() + 
  labs(title=paste("Simulated Cord pseudotime values from normal distribution,", n, "biological reps")) + 
  xlab("Pseudotime values")


ggplot(data=cmml_rand_normal, aes(x=pseudotime, group=sample)) + geom_density() + 
  labs(title=paste("Simulated CMML pseudotime values from normal distribution,", n, "biological reps")) +
  xlab("Pseudotime values")

```



### Simulate biological reps form poisson distribution
```{r}
# cord_rand_poissons <- rpois(n = nrow(cord_PTs), lambda = mean(cord_PTs$median_pseudotime))
# cmml_rand_poissons <- rpois(n = nrow(cmml_PTs), lambda = mean(cmml_PTs$median_pseudotime))

cord_rand_pois <- data.frame(sample1 = rpois(n=n_cord, lambda=cord_mean_pt))
cmml_rand_pois <- data.frame(sample1= rpois(n=n_cmml, lambda=cmml_mean_pt))

for (i in 2:n) {
  col_name <- paste("sample", i, sep="")
  cord_rand_pois[col_name] <- rpois(n=n_cord, lambda=cord_mean_pt)
  cmml_rand_pois[col_name] <- rpois(n=n_cmml, lambda=cmml_mean_pt)
}

cord_rand_pois <- pivot_longer(cord_rand_pois, 
                                 cols=c("sample1", "sample2", "sample3", "sample4", "sample5"), 
                                 names_to = "sample",
                                 values_to="pseudotime")

cmml_rand_pois <- pivot_longer(cmml_rand_pois, 
                                 cols=c("sample1", "sample2", "sample3", "sample4", "sample5"), 
                                 names_to = "sample",
                                 values_to="pseudotime")


ggplot(data=cord_rand_pois, aes(x=pseudotime, group=sample)) + geom_density() + 
  labs(title=paste("Simulated Cord pseudotime values from poisson distribution,", n, "biological reps")) + 
  xlab("Pseudotime values")


ggplot(data=cmml_rand_pois, aes(x=pseudotime, group=sample)) + geom_density() + 
  labs(title=paste("Simulated CMML pseudotime values from poisson distribution,", n, "biological reps")) +
  xlab("Pseudotime values")

```



